### ISSUE TITLE
Failing to handle cases like buffer deletion.

### ISSUE THREAD

**Issue by srihari93** [chrisbra/vim-autoread#2]
https://github.com/chrisbra/vim-autoread/blob/844cb71a3e3f42167c7ecf15c6f953811ae83c1c/autoload/autoread.vim#L12-L13

I am experiencing errors on line 13, when `len(bufinfo[0].windows) == 0` probably because I did `:bd` on the autoread buffer.

I can avoid these errors if I exited the callback when there are no windows:
```vim
    let bufinfo = getbufinfo(self.buffer)
    if len(bufinfo[0].windows) == 0
      return
    endif
    let winfo   = getwininfo(bufinfo[0].windows[0])
```
Am I breaking anything by doing this? If not, please merge https://github.com/chrisbra/vim-autoread/pull/3

**Comment by chrisbra** [comment]
closed by #3 h
